name: Rust CI

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]

jobs:
  check-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cargo Check
        run: cargo check --verbose

      - name: Cargo Test
        run: cargo test --verbose